#!/usr/bin/env python3
"""Per-file budget for rejected names: freeze the naming backlog, refuse growth.

`glossary.toml` holds one term per domain concept together with the spellings
that term replaces, plus shape rules for names nobody has written yet. This
script reads that file and reports every identifier in the Swift sources that
contradicts it.

A name already used in a hundred places cannot be fixed by adding a rule, and
excluding the files that carry it would exempt the names written tomorrow along
with the ones written yesterday. So the backlog is a budget: a file may not
exceed the number of rejected names it carries today, and a file that is not in
the budget may not carry a single one. The budget only ever shrinks. Once the
last entry reaches zero, `.naming-budget.json` is deleted and the check becomes
"no rejected spelling anywhere".

Only identifiers are counted. Comments and string literals are removed before
matching, so prose quoting a rejected spelling costs nothing — but the contents
of a string interpolation are kept, because `"\\(slotId)"` really is a reference
to the identifier. Where a rejected spelling is the correct name after all,
`[[exception]]` in `glossary.toml` records it together with its reason.

Four modes:

``check``
    Count today's findings and exit non-zero when a file is over its budget, or
    when a file with no budget has a finding at all. This is what CI runs.

``list``
    Print the findings themselves, for one path or for the whole tree.

``update``
    Rewrite the budget from today's counts. Run this after a rename, so the
    lower number is the one that has to be held. It refuses to record a count
    that grew unless ``--allow-raise`` says so, which is for the two ways a
    count rises without anyone writing a rejected name: a file moved and took
    its backlog along, or the glossary gained a term and the tree already
    spelled it the old way.

``render``
    Rewrite the generated sections of `docs/GLOSSARY.md` from the glossary.
    Those two tables are this script's input and output; a hand-maintained
    second copy of them would drift, and a rejected spelling that is listed but
    not enforced reads as enforced. ``--check`` verifies instead of writing.

Usage:

    python3 scripts/check_naming.py check
    python3 scripts/check_naming.py list wurstfingerKeyboard/Runtime
    python3 scripts/check_naming.py list --statistics
    python3 scripts/check_naming.py update
    python3 scripts/check_naming.py render --check
"""

from __future__ import annotations

import argparse
from collections import Counter
from dataclasses import dataclass
import json
from pathlib import Path
import re
import sys
import tomllib

REPO_ROOT = Path(__file__).resolve().parent.parent
GLOSSARY_FILE = REPO_ROOT / "glossary.toml"
BUDGET_FILE = REPO_ROOT / ".naming-budget.json"
GLOSSARY_DOC = REPO_ROOT / "docs" / "GLOSSARY.md"

SCANNED = ("wurstfinger", "wurstfingerKeyboard", "wurstfingerTests", "wurstfingerUITests")

MARKER_START = "<!-- generated by scripts/check_naming.py — do not edit: {name} -->"
MARKER_END = "<!-- /generated: {name} -->"


# ---------------------------------------------------------------------------
# The glossary
# ---------------------------------------------------------------------------


@dataclass(frozen=True)
class Term:
    """One canonical name and the spellings it replaces."""

    name: str
    zone: str
    definition: str
    rejected: tuple[str, ...]
    note: str


@dataclass(frozen=True)
class Pattern:
    """A shape rule: a regex over identifiers, with an allow-list.

    Terms catch the rejected spellings that exist today. Patterns catch the
    ones nobody has written yet — a `FooConfig` added next month matches the
    suffix rule without anyone having to extend the term list first.
    """

    id: str
    regex: str
    replacement: str
    rationale: str
    allowed: tuple[str, ...]
    applies_to: tuple[str, ...]

    def compiled(self) -> re.Pattern[str]:
        """Return the regex, with the allow-list turned into a lookahead."""
        return re.compile(_regex_with_allowed(self.regex, self.allowed))

    @property
    def checks_identifiers(self) -> bool:
        """Return whether this rule reads identifiers in the source."""
        return "identifier" in self.applies_to

    @property
    def checks_filenames(self) -> bool:
        """Return whether this rule reads file names.

        `GeometryUtils.swift` holds free extensions and declares no type, so a
        rule that only reads identifiers never sees the vague name at all.
        """
        return "filename" in self.applies_to


@dataclass(frozen=True)
class Glossary:
    """The parsed contents of `glossary.toml`."""

    terms: tuple[Term, ...]
    patterns: tuple[Pattern, ...]
    exceptions: dict[str, tuple[str, ...]]
    exception_reasons: dict[str, str]

    @property
    def aliases(self) -> dict[str, str]:
        """Map every rejected spelling to the term that replaces it."""
        return {alias: term.name for term in self.terms for alias in term.rejected}


def _regex_with_allowed(regex: str, allowed: tuple[str, ...]) -> str:
    """Return `regex` guarded by a negative lookahead for the allowed names.

    A pattern and its allow-list become one string rather than two things that
    have to be kept in step.
    """
    if not allowed:
        return regex
    alternatives = "|".join(re.escape(name) for name in sorted(allowed))
    return f"(?!(?:{alternatives})\\b){regex}"


def load_glossary(path: Path = GLOSSARY_FILE) -> Glossary:
    """Return the glossary, refusing a source that contradicts itself."""
    with path.open("rb") as handle:
        raw = tomllib.load(handle)

    terms = tuple(
        Term(
            name=entry["name"],
            zone=entry["zone"],
            definition=entry["definition"],
            rejected=tuple(entry.get("rejected", ())),
            note=entry.get("note", ""),
        )
        for entry in raw.get("term", ())
    )
    patterns = tuple(
        Pattern(
            id=entry["id"],
            regex=entry["regex"],
            replacement=entry["replacement"],
            rationale=entry.get("rationale", ""),
            allowed=tuple(entry.get("allowed", ())),
            applies_to=tuple(entry.get("applies_to", ("identifier",))),
        )
        for entry in raw.get("pattern", ())
    )

    canonical = {term.name for term in terms}
    seen_alias: dict[str, str] = {}
    for term in terms:
        if term.zone not in ("A", "B", "C"):
            _fail(f"{path.name}: `{term.name}` has zone `{term.zone}`, expected A, B or C")
        for alias in term.rejected:
            if alias in canonical:
                _fail(f"{path.name}: `{alias}` is both a term and rejected by `{term.name}`")
            if alias in seen_alias:
                _fail(f"{path.name}: `{alias}` is rejected by both `{seen_alias[alias]}` and `{term.name}`")
            seen_alias[alias] = term.name

    pattern_ids = {pattern.id for pattern in patterns}
    if len(pattern_ids) != len(patterns):
        _fail(f"{path.name}: two patterns share an id")
    for pattern in patterns:
        try:
            re.compile(_regex_with_allowed(pattern.regex, pattern.allowed))
        except re.error as error:
            _fail(f"{path.name}: pattern `{pattern.id}` has an invalid regex: {error}")
        unknown = set(pattern.applies_to) - {"identifier", "filename"}
        if unknown:
            _fail(f"{path.name}: pattern `{pattern.id}` applies to {sorted(unknown)}, expected identifier or filename")
        if not pattern.applies_to:
            _fail(f"{path.name}: pattern `{pattern.id}` applies to nothing")

    exceptions: dict[str, tuple[str, ...]] = {}
    reasons: dict[str, str] = {}
    for entry in raw.get("exception", ()):
        name = entry["name"]
        if name not in seen_alias and name not in pattern_ids:
            _fail(f"{path.name}: exception for `{name}`, which is neither a rejected spelling nor a pattern id")
        if not entry.get("reason"):
            _fail(f"{path.name}: exception for `{name}` has no reason")
        exceptions[name] = tuple(entry["paths"])
        reasons[name] = entry["reason"]

    return Glossary(terms=terms, patterns=patterns, exceptions=exceptions, exception_reasons=reasons)


def _fail(message: str) -> None:
    """Abort with a message; a self-contradicting glossary is a hard error."""
    print(f"error: {message}", file=sys.stderr)
    raise SystemExit(2)


# ---------------------------------------------------------------------------
# Reading Swift
# ---------------------------------------------------------------------------


def strip_noncode(source: str) -> str:
    """Return `source` with comments and string literals blanked out.

    Newlines are preserved so line numbers survive. The contents of a string
    interpolation are kept: `"\\(slotId)"` is a reference to the identifier,
    not prose about it. Raw string delimiters (`#"…"#`) are honoured, since
    inside them `\\(` is not an interpolation.
    """
    out: list[str] = []
    index = 0
    length = len(source)

    def keep_newlines(text: str) -> str:
        """Blank `text` while keeping its newlines, so line numbers survive."""
        return "".join(character if character == "\n" else " " for character in text)

    while index < length:
        character = source[index]

        if source.startswith("//", index):
            end = source.find("\n", index)
            end = length if end < 0 else end
            out.append(keep_newlines(source[index:end]))
            index = end
            continue

        if source.startswith("/*", index):
            depth, cursor = 1, index + 2
            while cursor < length and depth:
                if source.startswith("/*", cursor):
                    depth, cursor = depth + 1, cursor + 2
                elif source.startswith("*/", cursor):
                    depth, cursor = depth - 1, cursor + 2
                else:
                    cursor += 1
            out.append(keep_newlines(source[index:cursor]))
            index = cursor
            continue

        hashes = 0
        while index + hashes < length and source[index + hashes] == "#":
            hashes += 1
        quote_at = index + hashes
        if quote_at < length and source[quote_at] == '"':
            consumed, text = _read_string(source, index, hashes)
            out.append(text)
            index = consumed
            continue

        out.append(character)
        index += 1

    return "".join(out)


def _read_string(source: str, start: int, hashes: int) -> tuple[int, str]:
    """Consume one string literal from `start`; return (end index, replacement).

    The replacement blanks the literal but keeps interpolated expressions and
    every newline, so both line numbers and interpolated identifiers survive.
    An interpolated expression is stripped in turn, so a comment or a nested
    literal inside it does not re-enter the scan as code.
    """
    fence = "#" * hashes
    triple = source.startswith('"""', start + hashes)
    closing = f'"""{fence}' if triple else f'"{fence}'
    escape = f"\\{fence}"
    index = start + hashes + (3 if triple else 1)
    pieces: list[str] = [" " * (index - start)]
    length = len(source)

    while index < length:
        if source.startswith(closing, index):
            index += len(closing)
            pieces.append(" " * len(closing))
            break
        if source.startswith(escape + "(", index):
            depth, cursor = 1, index + len(escape) + 1
            while cursor < length and depth:
                if source[cursor] == "(":
                    depth += 1
                elif source[cursor] == ")":
                    depth -= 1
                cursor += 1
            pieces.append(" " * (len(escape) + 1))
            # The expression is code, but it can carry non-code of its own: a
            # comment, or a nested literal whose *contents* are prose again.
            # Stripping it recursively keeps the identifiers and drops the
            # rest; `strip_noncode` preserves length, so offsets still line up.
            pieces.append(strip_noncode(source[index + len(escape) + 1 : cursor - 1]))
            pieces.append(" ")
            index = cursor
            continue
        if source.startswith(escape, index):
            pieces.append(" " * (len(escape) + 1))
            index += len(escape) + 1
            continue
        pieces.append("\n" if source[index] == "\n" else " ")
        index += 1

    return index, "".join(pieces)


def swift_files(root: Path = REPO_ROOT, scope: Path | None = None) -> list[Path]:
    """Return the Swift sources to scan, sorted, honouring an optional scope."""
    files: list[Path] = []
    for directory in SCANNED:
        base = root / directory
        if not base.is_dir():
            continue
        files.extend(base.rglob("*.swift"))
    if scope is not None:
        resolved = scope.resolve()
        files = [path for path in files if resolved == path or resolved in path.parents]
    return sorted(files)


# ---------------------------------------------------------------------------
# Findings
# ---------------------------------------------------------------------------


@dataclass(frozen=True)
class Finding:
    """One identifier that contradicts the glossary."""

    path: str
    line: int
    name: str
    rejected: str
    replacement: str

    def __str__(self) -> str:
        """Return the finding as a `file:line: message` line."""
        return f"{self.path}:{self.line}: `{self.name}` is rejected, use {self.replacement}"


def _excepted(glossary: Glossary, key: str, path: str) -> bool:
    """Return whether `key` is waived for `path` by an `[[exception]]`."""
    return any(path == waived or path.startswith(f"{waived}/") for waived in glossary.exceptions.get(key, ()))


def scan(glossary: Glossary, files: list[Path], root: Path = REPO_ROOT) -> list[Finding]:
    """Return every finding in `files`, in file then line order."""
    aliases = glossary.aliases
    alias_patterns = {alias: re.compile(rf"\b{re.escape(alias)}\b") for alias in aliases}
    compiled_patterns = [(pattern, pattern.compiled()) for pattern in glossary.patterns]
    findings: list[Finding] = []

    for file in files:
        relative = str(file.relative_to(root))
        code = strip_noncode(file.read_text(encoding="utf-8", errors="replace"))
        starts = _line_starts(code)

        for pattern, regex in compiled_patterns:
            if not pattern.checks_filenames or _excepted(glossary, pattern.id, relative):
                continue
            if regex.search(file.stem):
                findings.append(Finding(relative, 1, file.name, pattern.id, pattern.replacement))

        for alias, regex in alias_patterns.items():
            if _excepted(glossary, alias, relative):
                continue
            replacement = aliases[alias]
            for match in regex.finditer(code):
                findings.append(
                    Finding(relative, _line_of(starts, match.start()), match.group(0), alias, f"`{replacement}`")
                )

        for pattern, regex in compiled_patterns:
            if not pattern.checks_identifiers or _excepted(glossary, pattern.id, relative):
                continue
            for match in regex.finditer(code):
                # A spelling that a term already rejects is reported once, under
                # that term, which names the concrete replacement. Counting it
                # twice would inflate every budget it appears in.
                if match.group(0) in aliases:
                    continue
                findings.append(
                    Finding(relative, _line_of(starts, match.start()), match.group(0), pattern.id, pattern.replacement)
                )

    return sorted(findings, key=lambda finding: (finding.path, finding.line, finding.name))


def _line_starts(text: str) -> list[int]:
    """Return the offset of every line start, for offset-to-line lookups."""
    starts = [0]
    for index, character in enumerate(text):
        if character == "\n":
            starts.append(index + 1)
    return starts


def _line_of(starts: list[int], offset: int) -> int:
    """Return the 1-based line number containing `offset`."""
    low, high = 0, len(starts) - 1
    while low < high:
        middle = (low + high + 1) // 2
        if starts[middle] <= offset:
            low = middle
        else:
            high = middle - 1
    return low + 1


def counts_by_file(findings: list[Finding]) -> dict[str, int]:
    """Return how many findings each file carries."""
    counter = Counter(finding.path for finding in findings)
    return {path: counter[path] for path in sorted(counter)}


def load_budget() -> dict[str, int]:
    """Return the recorded budget, or an empty one once the file is gone."""
    if not BUDGET_FILE.exists():
        return {}
    return json.loads(BUDGET_FILE.read_text(encoding="utf-8"))


# ---------------------------------------------------------------------------
# Modes
# ---------------------------------------------------------------------------


def mode_check(glossary: Glossary) -> int:
    """Fail when any file carries more rejected names than it is allowed."""
    findings = scan(glossary, swift_files())
    actual = counts_by_file(findings)
    budget = load_budget()

    over: list[str] = []
    for path, count in actual.items():
        allowed = budget.get(path, 0)
        if count > allowed:
            plural = "" if count == 1 else "s"
            over.append(f"{path}: {count} rejected name{plural}, budget {allowed}")

    if over:
        by_file: dict[str, list[Finding]] = {}
        for finding in findings:
            by_file.setdefault(finding.path, []).append(finding)
        print("Rejected names beyond the recorded budget:\n", file=sys.stderr)
        for line in over:
            path = line.split(":", 1)[0]
            print(f"  {line}", file=sys.stderr)
            for finding in by_file[path]:
                print(f"    {finding}", file=sys.stderr)
        print(
            "\nThe budget records the backlog as it stood; it may shrink, never grow."
            "\nRename the new occurrence, or add an [[exception]] to glossary.toml with a reason.",
            file=sys.stderr,
        )
        return 1

    stale = sorted(set(budget) - set(actual))
    if stale:
        print("Budget entries that no longer carry anything — run `update`:", file=sys.stderr)
        for path in stale:
            print(f"  {path}", file=sys.stderr)
        return 1

    total = sum(actual.values())
    print(f"OK — {total} rejected name{'s' if total != 1 else ''} in {len(actual)} files, all within budget.")
    return 0


def mode_list(glossary: Glossary, scope: Path | None, statistics: bool) -> int:
    """Print the findings, or a per-spelling tally with `--statistics`."""
    findings = scan(glossary, swift_files(scope=scope))
    if statistics:
        counter = Counter(finding.rejected for finding in findings)
        width = max((len(name) for name in counter), default=0)
        for name, count in sorted(counter.items(), key=lambda item: (-item[1], item[0])):
            print(f"{count:5}  {name:<{width}}")
        print(f"{sum(counter.values()):5}  total")
        return 0
    for finding in findings:
        print(finding)
    return 0


def mode_update(glossary: Glossary, allow_raise: bool) -> int:
    """Rewrite the budget from today's counts, refusing a silent increase."""
    actual = counts_by_file(scan(glossary, swift_files()))
    previous = load_budget()

    grown = {
        path: (previous[path], count)
        for path, count in actual.items()
        if path in previous and count > previous[path]
    }
    added = {path: count for path, count in actual.items() if path not in previous}
    if not allow_raise and (grown or added):
        for path, (was, now) in sorted(grown.items()):
            print(f"error: {path} grew from {was} to {now}", file=sys.stderr)
        for path, count in sorted(added.items()):
            print(f"error: {path} is not in the budget but carries {count}", file=sys.stderr)
        print(
            "\nThe budget only shrinks. Pass --allow-raise if a file moved and took its"
            "\nbacklog along, or if the glossary gained a term the tree already spelled"
            "\nthe old way.",
            file=sys.stderr,
        )
        return 1

    if not actual:
        if BUDGET_FILE.exists():
            BUDGET_FILE.unlink()
            print("The backlog is empty — removed .naming-budget.json.")
        else:
            print("The backlog is empty.")
        return 0

    BUDGET_FILE.write_text(json.dumps(actual, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    removed = sorted(set(previous) - set(actual))
    shrunk = sum(previous.get(path, 0) - count for path, count in actual.items() if count < previous.get(path, 0))
    print(f"Recorded {sum(actual.values())} rejected names in {len(actual)} files.")
    if shrunk or removed:
        print(f"  {shrunk} fewer than before; {len(removed)} file(s) now clean.")
    return 0


# ---------------------------------------------------------------------------
# Generated documentation
# ---------------------------------------------------------------------------


def _render_rejected(glossary: Glossary) -> str:
    """Return the Markdown table for GLOSSARY.md §7."""
    rows = [(f"`{alias}`", f"`{term.name}`") for term in glossary.terms for alias in term.rejected]
    rows += [(pattern.id.replace("_", " "), pattern.replacement) for pattern in glossary.patterns]
    lines = ["| Avoid | Write instead |", "| --- | --- |"]
    for avoid, instead in sorted(rows, key=lambda row: row[0].strip("`").lower()):
        lines.append(f"| {avoid} | {instead} |")
    return "\n".join(lines)


def _render_backlog(glossary: Glossary) -> str:
    """Return the Markdown table for GLOSSARY.md §8.

    Generated from the budget rather than hand-listed, so the section is
    exhaustive by construction instead of ending in "not exhaustive".
    """
    findings = scan(glossary, swift_files())
    counter = Counter(finding.rejected for finding in findings)
    if not counter:
        return "The backlog is empty: no source file carries a rejected spelling."

    pattern_ids = {pattern.id for pattern in glossary.patterns}
    replacement = {alias: f"`{name}`" for alias, name in glossary.aliases.items()}
    replacement.update({pattern.id: pattern.replacement for pattern in glossary.patterns})
    files = {name: len({f.path for f in findings if f.rejected == name}) for name in counter}

    lines = ["| Legacy spelling | Replacement | Sites | Files |", "| --- | --- | --- | --- |"]
    for name, count in sorted(counter.items(), key=lambda item: (-item[1], item[0])):
        shown = name.replace("_", " ") if name in pattern_ids else f"`{name}`"
        lines.append(f"| {shown} | {replacement[name]} | {count} | {files[name]} |")
    lines.append(f"| **total** | | **{sum(counter.values())}** | **{len(counts_by_file(findings))}** |")
    return "\n".join(lines)


def _render_exceptions(glossary: Glossary) -> str:
    """Return the Markdown table of path-scoped waivers."""
    if not glossary.exceptions:
        return "No waivers are recorded."
    lines = ["| Spelling | Where | Why |", "| --- | --- | --- |"]
    for name in sorted(glossary.exceptions):
        where = "<br>".join(f"`{path}`" for path in glossary.exceptions[name])
        lines.append(f"| `{name}` | {where} | {glossary.exception_reasons[name]} |")
    return "\n".join(lines)


def _replace_block(text: str, name: str, body: str) -> str:
    """Return `text` with the named generated block replaced by `body`."""
    start = MARKER_START.format(name=name)
    end = MARKER_END.format(name=name)
    if start not in text or end not in text:
        _fail(f"{GLOSSARY_DOC.name}: no generated block named `{name}`")
    head, rest = text.split(start, 1)
    _, tail = rest.split(end, 1)
    return f"{head}{start}\n\n{body}\n\n{end}{tail}"


def mode_render(glossary: Glossary, check_only: bool) -> int:
    """Rewrite (or verify) the generated tables in `docs/GLOSSARY.md`."""
    original = GLOSSARY_DOC.read_text(encoding="utf-8")
    updated = original
    for name, body in (
        ("rejected", _render_rejected(glossary)),
        ("backlog", _render_backlog(glossary)),
        ("exceptions", _render_exceptions(glossary)),
    ):
        updated = _replace_block(updated, name, body)

    if updated == original:
        print(f"{GLOSSARY_DOC.relative_to(REPO_ROOT)} is up to date.")
        return 0
    if check_only:
        print(
            f"error: {GLOSSARY_DOC.relative_to(REPO_ROOT)} is stale — "
            "run `python3 scripts/check_naming.py render`",
            file=sys.stderr,
        )
        return 1
    GLOSSARY_DOC.write_text(updated, encoding="utf-8")
    print(f"Rewrote the generated sections of {GLOSSARY_DOC.relative_to(REPO_ROOT)}.")
    return 0


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------


def main(argv: list[str] | None = None) -> int:
    """Parse arguments and run the selected mode."""
    parser = argparse.ArgumentParser(description="Check Swift identifiers against glossary.toml.")
    modes = parser.add_subparsers(dest="mode", required=True)

    modes.add_parser("check", help="fail when a file exceeds its recorded budget")

    listing = modes.add_parser("list", help="print the findings")
    listing.add_argument("path", nargs="?", type=Path, help="limit to a file or directory")
    listing.add_argument("--statistics", action="store_true", help="tally per rejected spelling")

    update = modes.add_parser("update", help="rewrite the budget from today's counts")
    update.add_argument("--allow-raise", action="store_true", help="permit a count to grow")

    render = modes.add_parser("render", help="rewrite the generated sections of docs/GLOSSARY.md")
    render.add_argument("--check", action="store_true", help="verify instead of writing")


    args = parser.parse_args(argv)
    glossary = load_glossary()

    if args.mode == "check":
        return mode_check(glossary)
    if args.mode == "list":
        return mode_list(glossary, args.path, args.statistics)
    if args.mode == "update":
        return mode_update(glossary, args.allow_raise)
    return mode_render(glossary, args.check)


if __name__ == "__main__":
    raise SystemExit(main())
